<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PartSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $parts = [
            // ── Ganti Oli Mesin ──────────────────────────────────────────────
            [
                'sku'       => 'OLI-TOY-001',
                'name'      => 'Oli Mesin Toyota 1L (SAE 10W-40)',
                'category'  => 'mesin',
                'unit'      => 'liter',
                'price'     => 65000,
                'stock'     => 80,
                'min_stock' => 20,
            ],
            [
                'sku'       => 'OLI-HON-001',
                'name'      => 'Oli Mesin Honda 1L (SAE 10W-30)',
                'category'  => 'mesin',
                'unit'      => 'liter',
                'price'     => 60000,
                'stock'     => 75,
                'min_stock' => 20,
            ],
            [
                'sku'       => 'OLI-SYN-001',
                'name'      => 'Oli Mesin Synthetic 1L (SAE 5W-30)',
                'category'  => 'mesin',
                'unit'      => 'liter',
                'price'     => 95000,
                'stock'     => 50,
                'min_stock' => 15,
            ],
            [
                'sku'       => 'FIL-OLI-001',
                'name'      => 'Filter Oli Universal',
                'category'  => 'mesin',
                'unit'      => 'pcs',
                'price'     => 45000,
                'stock'     => 40,
                'min_stock' => 10,
            ],
            [
                'sku'       => 'FIL-OLI-002',
                'name'      => 'Filter Oli Toyota Avanza/Rush',
                'category'  => 'mesin',
                'unit'      => 'pcs',
                'price'     => 55000,
                'stock'     => 30,
                'min_stock' => 8,
            ],
            [
                'sku'       => 'DRN-PLG-001',
                'name'      => 'Drain Plug / Baut Pembuang Oli',
                'category'  => 'mesin',
                'unit'      => 'pcs',
                'price'     => 15000,
                'stock'     => 50,
                'min_stock' => 10,
            ],

            // ── Tune Up Mesin ────────────────────────────────────────────────
            [
                'sku'       => 'BUS-NGK-001',
                'name'      => 'Busi NGK Standard (per pcs)',
                'category'  => 'mesin',
                'unit'      => 'pcs',
                'price'     => 35000,
                'stock'     => 60,
                'min_stock' => 16,
            ],
            [
                'sku'       => 'BUS-NGK-002',
                'name'      => 'Busi NGK Iridium (per pcs)',
                'category'  => 'mesin',
                'unit'      => 'pcs',
                'price'     => 85000,
                'stock'     => 40,
                'min_stock' => 8,
            ],
            [
                'sku'       => 'FIL-UDA-001',
                'name'      => 'Filter Udara Universal',
                'category'  => 'mesin',
                'unit'      => 'pcs',
                'price'     => 75000,
                'stock'     => 25,
                'min_stock' => 8,
            ],
            [
                'sku'       => 'FIL-UDA-002',
                'name'      => 'Filter Udara Toyota Avanza',
                'category'  => 'mesin',
                'unit'      => 'pcs',
                'price'     => 90000,
                'stock'     => 20,
                'min_stock' => 5,
            ],
            [
                'sku'       => 'CAI-REM-001',
                'name'      => 'Cairan Rem DOT 3 (500ml)',
                'category'  => 'mesin',
                'unit'      => 'botol',
                'price'     => 45000,
                'stock'     => 30,
                'min_stock' => 10,
            ],
            [
                'sku'       => 'CAI-RAD-001',
                'name'      => 'Air Radiator Coolant (1L)',
                'category'  => 'mesin',
                'unit'      => 'liter',
                'price'     => 35000,
                'stock'     => 40,
                'min_stock' => 10,
            ],
            [
                'sku'       => 'CAI-AKI-001',
                'name'      => 'Air Aki Zuur (1L)',
                'category'  => 'kelistrikan',
                'unit'      => 'liter',
                'price'     => 20000,
                'stock'     => 35,
                'min_stock' => 10,
            ],
            [
                'sku'       => 'PLT-KOP-001',
                'name'      => 'Platinum / Korek Api Tune Up',
                'category'  => 'mesin',
                'unit'      => 'set',
                'price'     => 25000,
                'stock'     => 20,
                'min_stock' => 5,
            ],

            // ── Servis AC Mobil ──────────────────────────────────────────────
            [
                'sku'       => 'FRE-R134-001',
                'name'      => 'Freon AC R134a (per 100gr)',
                'category'  => 'ac',
                'unit'      => 'gram',
                'price'     => 8000,
                'stock'     => 2000,
                'min_stock' => 500,
            ],
            [
                'sku'       => 'FRE-R32-001',
                'name'      => 'Freon AC R32 (per 100gr)',
                'category'  => 'ac',
                'unit'      => 'gram',
                'price'     => 10000,
                'stock'     => 1500,
                'min_stock' => 400,
            ],
            [
                'sku'       => 'OLI-KOM-001',
                'name'      => 'Oli Kompresor AC (100ml)',
                'category'  => 'ac',
                'unit'      => 'ml',
                'price'     => 35000,
                'stock'     => 20,
                'min_stock' => 5,
            ],
            [
                'sku'       => 'FIL-KAB-001',
                'name'      => 'Filter Kabin / Filter AC Universal',
                'category'  => 'ac',
                'unit'      => 'pcs',
                'price'     => 55000,
                'stock'     => 20,
                'min_stock' => 5,
            ],
            [
                'sku'       => 'FIL-KAB-002',
                'name'      => 'Filter Kabin Toyota Avanza/Xenia',
                'category'  => 'ac',
                'unit'      => 'pcs',
                'price'     => 70000,
                'stock'     => 15,
                'min_stock' => 4,
            ],
            [
                'sku'       => 'SPR-BLW-001',
                'name'      => 'Sabuk / Belt Kompresor AC',
                'category'  => 'ac',
                'unit'      => 'pcs',
                'price'     => 120000,
                'stock'     => 10,
                'min_stock' => 3,
            ],

            // ── Perbaikan Kelistrikan ────────────────────────────────────────
            [
                'sku'       => 'FUS-SET-001',
                'name'      => 'Sekering Set (assorted)',
                'category'  => 'kelistrikan',
                'unit'      => 'set',
                'price'     => 25000,
                'stock'     => 30,
                'min_stock' => 10,
            ],
            [
                'sku'       => 'AKI-GS-001',
                'name'      => 'Aki GS Astra NS40ZL (35Ah)',
                'category'  => 'kelistrikan',
                'unit'      => 'pcs',
                'price'     => 650000,
                'stock'     => 8,
                'min_stock' => 2,
            ],
            [
                'sku'       => 'AKI-GS-002',
                'name'      => 'Aki GS Astra NS60L (45Ah)',
                'category'  => 'kelistrikan',
                'unit'      => 'pcs',
                'price'     => 850000,
                'stock'     => 6,
                'min_stock' => 2,
            ],
            [
                'sku'       => 'LMP-HED-001',
                'name'      => 'Bohlam Headlamp H4 55W',
                'category'  => 'kelistrikan',
                'unit'      => 'pcs',
                'price'     => 45000,
                'stock'     => 20,
                'min_stock' => 6,
            ],
            [
                'sku'       => 'LMP-LED-001',
                'name'      => 'Bohlam LED H4 (sepasang)',
                'category'  => 'kelistrikan',
                'unit'      => 'set',
                'price'     => 185000,
                'stock'     => 12,
                'min_stock' => 4,
            ],
            [
                'sku'       => 'KBL-ACU-001',
                'name'      => 'Kabel Aki Positif/Negatif (per meter)',
                'category'  => 'kelistrikan',
                'unit'      => 'meter',
                'price'     => 22000,
                'stock'     => 50,
                'min_stock' => 10,
            ],
            [
                'sku'       => 'REL-STR-001',
                'name'      => 'Relay Starter Universal',
                'category'  => 'kelistrikan',
                'unit'      => 'pcs',
                'price'     => 55000,
                'stock'     => 10,
                'min_stock' => 3,
            ],

            // ── Perbaikan Bodi ───────────────────────────────────────────────
            [
                'sku'       => 'DMP-BDY-001',
                'name'      => 'Dempul Bodi (500gr)',
                'category'  => 'bodi',
                'unit'      => 'kaleng',
                'price'     => 35000,
                'stock'     => 20,
                'min_stock' => 5,
            ],
            [
                'sku'       => 'CAT-PRM-001',
                'name'      => 'Cat Primer Epoxy (400ml spray)',
                'category'  => 'bodi',
                'unit'      => 'kaleng',
                'price'     => 55000,
                'stock'     => 15,
                'min_stock' => 4,
            ],
            [
                'sku'       => 'AMP-LST-001',
                'name'      => 'Amplas Bodi P80 (per lembar)',
                'category'  => 'bodi',
                'unit'      => 'lembar',
                'price'     => 5000,
                'stock'     => 100,
                'min_stock' => 30,
            ],
            [
                'sku'       => 'AMP-LST-002',
                'name'      => 'Amplas Bodi P180 (per lembar)',
                'category'  => 'bodi',
                'unit'      => 'lembar',
                'price'     => 5000,
                'stock'     => 100,
                'min_stock' => 30,
            ],
            [
                'sku'       => 'AMP-LST-003',
                'name'      => 'Amplas Bodi P400 (per lembar)',
                'category'  => 'bodi',
                'unit'      => 'lembar',
                'price'     => 6000,
                'stock'     => 80,
                'min_stock' => 20,
            ],
            [
                'sku'       => 'PLT-BOD-001',
                'name'      => 'Plastik Masking Tape (24mm)',
                'category'  => 'bodi',
                'unit'      => 'roll',
                'price'     => 18000,
                'stock'     => 30,
                'min_stock' => 8,
            ],

            // ── Spooring & Balancing ─────────────────────────────────────────
            [
                'sku'       => 'TIM-BLC-001',
                'name'      => 'Timah Balancing (per 5gr)',
                'category'  => 'mesin',
                'unit'      => 'gram',
                'price'     => 500,
                'stock'     => 5000,
                'min_stock' => 1000,
            ],
            [
                'sku'       => 'TIM-BLC-002',
                'name'      => 'Timah Balancing Clip (per set 4 ban)',
                'category'  => 'mesin',
                'unit'      => 'set',
                'price'     => 35000,
                'stock'     => 50,
                'min_stock' => 10,
            ],
            [
                'sku'       => 'ANT-KRT-001',
                'name'      => 'Angin / Nitrogen Ban (per ban)',
                'category'  => 'mesin',
                'unit'      => 'pcs',
                'price'     => 10000,
                'stock'     => 999,
                'min_stock' => 100,
            ],

            // ── Consumables Umum ─────────────────────────────────────────────
            [
                'sku'       => 'GRS-GEM-001',
                'name'      => 'Gemuk / Grease (per 200gr)',
                'category'  => 'mesin',
                'unit'      => 'kaleng',
                'price'     => 28000,
                'stock'     => 30,
                'min_stock' => 8,
            ],
            [
                'sku'       => 'KIN-CAR-001',
                'name'      => 'Cairan Pembersih Karburator (400ml)',
                'category'  => 'mesin',
                'unit'      => 'kaleng',
                'price'     => 45000,
                'stock'     => 20,
                'min_stock' => 5,
            ],
            [
                'sku'       => 'KIN-ENG-001',
                'name'      => 'Engine Flush / Pembersih Mesin (300ml)',
                'category'  => 'mesin',
                'unit'      => 'botol',
                'price'     => 38000,
                'stock'     => 25,
                'min_stock' => 6,
            ],
            [
                'sku'       => 'WIP-RAG-001',
                'name'      => 'Kain Lap Majun (per kg)',
                'category'  => 'lainnya',
                'unit'      => 'kg',
                'price'     => 15000,
                'stock'     => 20,
                'min_stock' => 5,
            ],
            [
                'sku'       => 'GLV-LAT-001',
                'name'      => 'Sarung Tangan Latex (per box/100pcs)',
                'category'  => 'lainnya',
                'unit'      => 'box',
                'price'     => 65000,
                'stock'     => 10,
                'min_stock' => 3,
            ],
        ];

        foreach ($parts as $part) {
            DB::table('parts')->insertOrIgnore([
                ...$part,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        $this->command->info('✅ ' . count($parts) . ' suku cadang berhasil di-seed.');
    }
}
